### ISSUE TITLE
ObtainedWebGpuAdapter was given a null GpuAdapter :-(

### ISSUE THREAD

**Issue by kant2002** [yowl/CSharpWebGpu#3]
see https://github.com/juj/wasm_webgpu/pull/23

Issue was with too strict WasmWebGPU checks. Hopefully they allow land PR and everything would be great.

**Comment by juj** [comment]
Sorry, this was actually a regression caused by this commit: https://github.com/juj/wasm_webgpu/commit/77cc360413c3ec3c51571647a45ea37f74a34276 . Fixed in https://github.com/juj/wasm_webgpu/commit/63e8b0c5b9618d6ff4bba46c59ccefe0852d86ec (there are now [9 different possible WebGPU extension features](https://github.com/juj/wasm_webgpu/blob/63e8b0c5b9618d6ff4bba46c59ccefe0852d86ec/lib/lib_webgpu.h#L215-L224))

**Comment by kant2002** [comment]
@juj I recheck, and definitely both my laptops has 9 features :) so I'm definitely happy. Thank you!
